export const ADD_TO_BOOK_CART = "ADD_TO_BOOK_CART";

export const REMOVE_CART_BOOK_ITEM = "REMOVE_CART_BOOK_ITEM";

export const ADD_TO_EBOOK_CART = "ADD_TO_EBOOK_CART";

export const REMOVE_CART_EBOOK_ITEM = "REMOVE_CART_EBOOK_ITEM";

export const ADD_TO_PACKAGE_CART = "ADD_TO_PACKAGE_CART";

export const REMOVE_CART_PACKAGE_ITEM = "REMOVE_CART_PACKAGE_ITEM";
